### ISSUE TITLE
Problem with lists (both ul and ol)

### ISSUE THREAD

**Issue by NigelRoth** [Aymkdn/html-to-pdfmake#71] opened 2020-10-05 14:18 UTC
Love your code and sorry to be a nuisance but I'm getting unpredictable results from simple lists
```
`<p>desc</p><ul><li>line 1</li><li>line 2</li></ul>
<ol><li>line 1</li><li>line 2</li></ol>`
```

Works fine in your playground but creates this when made
[file-7.pdf](https://github.com/Aymkdn/html-to-pdfmake/files/5327926/file-7.pdf)

Help much appreciated.

**Comment by NigelRoth** [comment] 2020-10-05 15:56
It seems to be a whitespace problem but I'm not sure how to eliminate it in VBScript - Trim only removes from beginning and end.
I'm already removing vbCrlf

`<h1>s</h1><p>art</p><p>desc</p><ul>	<li>line 1</li>	<li>line 2</li></ul><ol>	<li>line 1</li>	<li>line 2</li></ol>`

**Comment by Aymkdn** [comment] 2020-10-05 16:03
Do you pass any kind of parameters to `html-to-pdfmake` or `PDFMake`?

**Comment by NigelRoth** [comment] 2020-10-05 16:14
Not that I know of.  The text is created by users in a CKEditor TextArea which is stored in a MYSQL LONGTEXT field.  I cannot completely control the user entry.  I could send you a link but would not wish to publish it.

It is retrieved with 

```
	Set vNews = Server.CreateObject("ADODB.Recordset")
	vNews.ActiveConnection = "dsn=dataxxx"
	vNews.CursorType = 0
	vNews.CursorLocation = 2
	vNews.LockType = 1
	strsql = "SELECT * FROM news WHERE itemno="&itemno
	vNews.Source = strsql
	vNews.Open()
	While Not vNews.EOF
		pdf = pdf &"<h1>" &Replace(vNews("Subject"), vbCrLf, "")&"</h1>"
		pdf = pdf &Replace(vNews("Article"), vbCrLf, "")
		pdf = pdf &Replace(vNews("Description"), vbCrLf, "")
		vNews.MoveNext
	Wend
	vNews.Close
	Set vNews = Nothing
```
and then pdf is passed to your code with

```
`    var val = htmlToPdfmake('<%= "<img width=""200"" src="&logo&"/>"&pdf %>');
    var dd = {content:val};
    pdfMake.createPdf(dd).download();
`
```
along with the image "logo" in Base64

Perhaps your code should ignore whitespaces between html tags?

**Comment by Aymkdn** [comment] 2020-10-05 16:17
Mmmhhhh… OK, I found there is a problem, indeed.

I'll have to investigate to find the cause and find a solution. It could take a few days.

**Comment by NigelRoth** [comment] 2020-10-05 16:23
Many thanks

**Comment by Aymkdn** [comment] 2020-10-06 13:41
Fixed in v2.1.0

**Comment by NigelRoth** [comment] 2020-10-06 14:04
Great thanks.  Assume you will upload to cdn in due course but working fine.
[file-1.pdf](https://github.com/Aymkdn/html-to-pdfmake/files/5334377/file-1.pdf)

**Comment by Aymkdn** [comment] 2020-10-06 14:26
It's already on the CDN: https://cdn.jsdelivr.net/npm/html-to-pdfmake@latest/

**Closed by Aymkdn** 2020-10-06 14:26 UTC
Labels: bug

**Comment by rbarbeito** [comment] 2021-06-30 16:28
I am trying to generate a pdf from a query to a database, where the information has HTML code, like lists. `<p><strong>DDDDD</strong></p><ol><li>jkdbkjdf</li><li>bjdbfkjadsf</li><li>kjdnfkadf</li></ol><ul><li>kjdfkajdsfnla</li></ul><p><br></p><p>ljasdbfjads ajdhfpija sdifhapisd iasdpfj pOSDJF POIASJDF</p>`

after installing `pdfmake` and `html-to-pdfmake`, i import them into my component.ts

    const pdfMake = require('node_modules/pdfmake/build/pdfmake')
    const pdfFonts = require('node_modules/pdfmake/build/vfs_fonts')
    pdfMake.vfs = pdfFonts.pdfMake.vfs
    const htmlToPdfmake = require('html-to-pdfmake')

at some point I send to call the method where it is generated creates my pdf

    savePDF() {
        console.log(this.reConsulta)
    
        const documentDefinition = {
          pageSize: 'A5',
          // by default we use portrait, you can change it to landscape if you wish
          pageOrientation: 'landscape',
          // [left, top, right, bottom] or [horizontal, vertical] or just a number for equal margins
          pageMargins: [5, 100, 5, 10],
    
          content: [
            { text: htmlToPdfmake(this.reConsulta.medicamentos) },
            { text: htmlToPdfmake(this.reConsulta.metodo), absolutePosition: { x: 320, y: 100 } },
          ],
        }
    
        pdfMake.createPdf(documentDefinition).open()
      }

at this moment `this.reConsulta.medicamentos` has the value of the previous list `<p><strong>DDDDD</strong></p><ol><li>jkdbkjdf</li><li>bjdbfkjadsf</li><li>kjdnfkadf</li></ol><ul><li>kjdfkajdsfnla</li></ul><p><br></p><p>ljasdbfjads ajdhfpija sdifhapisd iasdpfj pOSDJF POIASJDF</p>`

but cdo creates the pdf the list is not displayed, however other html tags like `<b> </b>` `<i> </i>` are formatted without problems.


![image](https://user-images.githubusercontent.com/14133027/123997476-0d83df00-d996-11eb-8b19-671529c34d4d.png)

**Comment by Aymkdn** [comment] 2021-07-01 08:00
You'll have to find the problem by yourself, because when I test with `<p><strong>DDDDD</strong></p><ol><li>jkdbkjdf</li><li>bjdbfkjadsf</li><li>kjdnfkadf</li></ol><ul><li>kjdfkajdsfnla</li></ul><p><br></p><p>ljasdbfjads ajdhfpija sdifhapisd iasdpfj pOSDJF POIASJDF</p>`, it looks good to me:
![image](https://user-images.githubusercontent.com/946315/124088363-27cfc280-da53-11eb-8e33-5a5a25c1d62b.png)

**Comment by rbarbeito** [comment] 2021-07-01 12:27
Exactly that is the problem, I did all the tests on that website, and it worked perfectly for me, I followed all the indications for the implementation in angular, and I found the error. I will continue looking for what may be my error or problem that I do not obtain the expected result, greetings

**Comment by rbarbeito** [comment] 2021-07-01 13:21
I tried other options until I noticed something peculiar. if I use this code directly.

```
let htmlMedicamentos = htmlToPdfmake('<ol><li>dd</li><li>d</li></ol>')
const documentDefinition={content:htmlMedicamentos}
pdfMake.createPdf(documentDefinition).open()
```
everything works wonders

![image](https://user-images.githubusercontent.com/14133027/124129630-9442c580-da43-11eb-84a3-7ab1d2dd3fae.png)

but if I try to format the document with pdfmake it is where what is expected does not happen.

`var htmlMedicamentos = htmlToPdfmake( '<ol><li>dd</li><li>d</li></ol>' );`


```
const documentDefinition = {
      pageSize: 'A5',
      // by default we use portrait, you can change it to landscape if you wish
      pageOrientation: 'landscape',
      // [left, top, right, bottom] or [horizontal, vertical] or just a number for equal margins
      pageMargins: [20, 100, 20, 10],

      content: [
        {
          columns: [
            { width: '48%', text: htmlMedicamentos },
            { width: '45%', text: this.reConsulta.metodo, absolutePosition: { x: 320, y: 100 } },
          ],
          columnGap: 5,
        },
      ],
    }


    pdfMake.createPdf(documentDefinition).open()
```

**Comment by Aymkdn** [comment] 2021-07-01 13:28
So it might be a bug with PDFMake? In that case you need to post on the PDFMake Github repository.

**Comment by rbarbeito** [comment] 2021-07-01 14:20
Thanks for helping me, finally I will look for a solution

![image](https://user-images.githubusercontent.com/14133027/124139558-5b0f5300-da4d-11eb-8b1b-9a89e6074c6d.png)

**Comment by Aymkdn** [comment] 2021-07-01 14:37
Don't talk about `html-to-pdfmake`. But display the end result of your code.

So instead of posting:
```js
const documentDefinition = {
      pageSize: 'A5',
      // by default we use portrait, you can change it to landscape if you wish
      pageOrientation: 'landscape',
      // [left, top, right, bottom] or [horizontal, vertical] or just a number for equal margins
      pageMargins: [20, 100, 20, 10],

      content: [
        {
          columns: [
            { width: '48%', text: htmlMedicamentos },
            { width: '45%', text: this.reConsulta.metodo, absolutePosition: { x: 320, y: 100 } },
          ],
          columnGap: 5,
        },
      ],
    }
```

You should post:
```js
const documentDefinition = {
      pageSize: 'A5',
      // by default we use portrait, you can change it to landscape if you wish
      pageOrientation: 'landscape',
      // [left, top, right, bottom] or [horizontal, vertical] or just a number for equal margins
      pageMargins: [20, 100, 20, 10],

      content: [
        {
          columns: [
            { width: '48%', text: [
    {
      "nodeName": "OL",
      "style": [
        "html-ol"
      ],
      "ol": [
        {
          "text": "dd",
          "nodeName": "LI",
          "style": [
            "html-li",
            "html-ol"
          ]
        },
        {
          "text": "d",
          "nodeName": "LI",
          "style": [
            "html-li",
            "html-ol"
          ]
        }
      ]
    }
  ] },
            { width: '45%', text: this.reConsulta.metodo, absolutePosition: { x: 320, y: 100 } },
          ],
          columnGap: 5,
        },
      ],
    }
```

As I said, the issue happends AFTER `html-to-pdfmake` has built the code. So you have to provide to PDFMake author only the parts that is related to PDFMake.

**Comment by rbarbeito** [comment] 2021-07-02 16:35
@Aymkdn Thanks for all the guidance and suggestions, the error was in the construction of the columns with pdfMake.
