### ISSUE TITLE
Table: Not equal number of table data cells inside table rows make the Content corrupt for PDFMake

### ISSUE THREAD

**Issue by Raul52** [Aymkdn/html-to-pdfmake#156] opened 2022-11-03 15:37 UTC
Hello,

I have identified an issue while using https://aymkdn.github.io/html-to-pdfmake/index.html
This also happens in my application.

If you insert:

**Erroneous Input:**
````html
<table border="1">
	<tbody>
		<tr>
			<td>Úřední název</td>
			<td>IČO</td>
			<td>Nabídková cena bez DPH</td>
			<td>Nabídková cena s DPH</td>
			<td>Obec</td>
		</tr>
		<tr class="rgNoRecords">
			<td>
			<div>Nenalezeny žádné záznamy k zobrazení</div>
			</td>
		</tr>
	</tbody>
</table>
````

You will see that the following error is thrown when trying to generate the PDF.
`Uncaught (in promise) Malformed table row, a cell is undefined.`

If you manipulate the input and add as many `<td>` as there are in the first `<tr>` you will see that the PDF is generated correctly.

**Valid Input:**
````html
<table border="1">
	<tbody>
		<tr>
			<td>Úřední název</td>
			<td>IČO</td>
			<td>Nabídková cena bez DPH</td>
			<td>Nabídková cena s DPH</td>
			<td>Obec</td>
		</tr>
		<tr class="rgNoRecords">
			<td>
			<div>Nenalezeny žádné záznamy k zobrazení</div>
			</td>
			<td>
			<div>Nenalezeny žádné záznamy k zobrazení</div>
			</td>
			<td>
			<div>Nenalezeny žádné záznamy k zobrazení</div>
			</td>
			<td>
			<div>Nenalezeny žádné záznamy k zobrazení</div>
			</td>
			<td>
			<div>Nenalezeny žádné záznamy k zobrazení</div>
			</td>
		</tr>
	</tbody>
</table>
````

Can someone advise me on how to continue?

**Comment by Raul52** [comment] 2022-11-04 07:03
Furthermore, you can see that if you have the `colspan` attribute with a value **lower** than the other's table row `<td>` you will have the same error.

Erroneous input:
```HTML
<table border="1">
	<tbody>
		<tr>
			<td>Úřední název</td>
			<td>IČO</td>
			<td>Nabídková cena bez DPH</td>
			<td>Nabídková cena s DPH</td>
			<td>Obec</td>
		</tr>
		<tr class="rgNoRecords">
			<td colspan=4>
			<div>Nenalezeny žádné záznamy k zobrazení</div>
			</td>
		</tr>
	</tbody>
</table>
```

Exception thrown:
`Uncaught (in promise) Malformed table row, a cell is undefined.`

If you have the `colspan` with a value **higher** than the other's table row `<td>` we will get a different exception.

Erroneous input:
```HTML
<table border="1">
	<tbody>
		<tr>
			<td>Úřední název</td>
			<td>IČO</td>
			<td>Nabídková cena bez DPH</td>
			<td>Nabídková cena s DPH</td>
			<td>Obec</td>
		</tr>
		<tr class="rgNoRecords">
			<td colspan=6>
			<div>Nenalezeny žádné záznamy k zobrazení</div>
			</td>
		</tr>
	</tbody>
</table>
```

Exception thrown:
`Uncaught (in promise) Error: unsupported number: NaN`

But if you have the `colspan` with a value that is **equal** to the other's table row `<td>` we will get the desired generated PDF.

Valid input:
```HTML
<table border="1">
	<tbody>
		<tr>
			<td>Úřední název</td>
			<td>IČO</td>
			<td>Nabídková cena bez DPH</td>
			<td>Nabídková cena s DPH</td>
			<td>Obec</td>
		</tr>
		<tr class="rgNoRecords">
			<td colspan=5>
			<div>Nenalezeny žádné záznamy k zobrazení</div>
			</td>
		</tr>
	</tbody>
</table>
```

**Comment by Aymkdn** [comment] 2022-11-04 08:58
The HTML code needs to be exact. If the browser is able to make things work even with bad numbers, it's not the case of this framework. So, is it your problem? Are you trying to put incorrect numbers of TD or colspan? If yes, then you're doing it the wrong way. If no, then I'll need to investigate. 

I'm on vacation in a foreign country for the next 8 days. So you may expect some time before I can look at it.

**Comment by Aymkdn** [comment] 2022-11-13 13:31
I'm back and I looked at your example. As I said, you need to put a valid numbers of TD/colspan to make it work. So it's not a bug. I'm closing this issue.

**Closed by Aymkdn** 2022-11-13 13:31 UTC
